[build]
  # Command to build the Next.js app
  command = "npm run build"
  
  # Directory to publish, Next.js uses the ".next" directory
  publish = ".next"

  # Set environment variables (if needed)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
